baseurl = "https://productonomics.com/"
languageCode = "ja"
title = "Productonomics - The hidden side of products"
theme = 'hestia-pure'

[author]
 author = 'Umang Sehgal'
 profile = 'I am a Technical Program Manager working in San Francisco, California. Proud UW Alum. Hailing from India!'
 image = 'image/theme/profile.jpg'

[Params]
 localeOgp = "ja"
 description = "A diary in San Francisco."
 keywords = "Product Manager, Product Managemenet, Product Market Fit, Growth"
 twitter = "SehgalUmang"
 github = "umangsehgal"
 linkedin = "umangsehgal"
 googleanalytics = "UA-137481837-2"
 googlecustomsearch = ""
