baseURL = "http://productonomics.com/"
languageCode = "en-us"
title = "Productonomics"
theme="tale-hugo"

name = "Tale"
license = "MIT"
licenselink = "https://github.com/EmielH/tale-hugo/blob/master/LICENSE"
description = "Productonomics aims to help investors and consumers to gain access to detailed analysis of growth startups and companies in the SaaS space. It also produces weekly content on tech topics that Product Managers would want to seek concise information on."
homepage = "https://github.com/EmielH/tale-hugo"
tags = ["Startups", "Product", "Investments", "Cloud", "AWS", "Machine Learning", "AI", "Market Fit", "Analytics"]
features = ["pagination"]
min_version = "0.50"

[author]
  name = "Umang Sehgal"
  homepage = "https://www.linkedin.com/in/umangsehgal/"
